//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppPresenze
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dipendenti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dipendenti()
        {
            this.FogliPresenze = new HashSet<FogliPresenze>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public string Sede { get; set; }
        public string CodiceTeam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FogliPresenze> FogliPresenze { get; set; }
    }
}
