//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppFogliPresenze
{
    using System;
    using System.Collections.Generic;
    
    public partial class FogliPresenze
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FogliPresenze()
        {
            this.OreLavorative = new HashSet<OreLavorative>();
        }
    
        public int Id { get; set; }
        public int DipendenteId { get; set; }
        public int Anno { get; set; }
        public int Mese { get; set; }
        public string Stato { get; set; }
    
        public virtual Dipendenti Dipendenti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OreLavorative> OreLavorative { get; set; }
    }
}
